FROM golang:1.17

RUN go version
ENV GOPATH=/

COPY ./ ./

#install psql
RUN apt-get clean && apt-get update
RUN apt-get -y install postgresql-client

#make wait-for-postgres.sh executable
#RUN chmod +x wait-for-postgres.sh

#build go app
#RUN go mod download
#RUN go build -o main .

#CMD ["./main"]